### ISSUE TITLE
tracefs: support for syscall event trace points

### ISSUE THREAD

**Issue by 65278** [adjust/gentoo-overlay#130]
While debugging high syscall load on attribution-5, I wanted to use perf with perf stat to monitor the syscalls.

This requires the tracefs to have events/syscalls. This is configured by CONFIG_FTRACE_SYSCALLS as far as I can tell. I can not find any meaningful documentation on performance overhead for these static tracepoints, but it is claimed to be very low.

**Comment by patricklauer** [comment]
Enabled in 4.15+
