### ISSUE TITLE
gentoo-kernel: include System.map

### ISSUE THREAD

**Issue by 65278** [adjust/gentoo-overlay#151]
The eclass running depmod (linux-mod.eclass), post to install of an out of tree kernel module, doesn't run depmod if there's no System.map for the kernel available. This is painful when upgrading bagger servers for example, because you only notice that zfs.ko can't be found when you reboot them.

**Comment by alip** [comment]
Indeed. This is generally useful when fiddling with kernel modules. +1

**Comment by xmhd** [comment]
new kernel ebuild will fix this
