### ISSUE TITLE
app-admin/schaufel: installs /schaufel 

### ISSUE THREAD

**Issue by patricklauer** [adjust/gentoo-overlay#194]
```
 * The ebuild is installing to one or more unexpected paths:
 *
 *   /schaufel
```
looks like a minor ebuild bug, file also exists as `/usr/bin/schaufel`

**Comment by 65278** [comment]
That's one of the points about the makefile being broken. There are a couple more. Surgically fix or try to get a little more out of the next schaufel release build system?

**Comment by patricklauer** [comment]
Make build system pretty and it'll be fixed through that. Mostly cosmetic issue.
