### ISSUE TITLE
nmis-4.3.7c breaks with perl-5.26.2

### ISSUE THREAD

**Issue by alip** [adjust/gentoo-overlay#207]
Unescaped braces were deprecated in 5.22 and since 5.26 they cause a syntax error rather than emitting a warning. Below is the diff to fix a codepath that affects our cron entries for nmis.

1. We want the ebuild to take care of that.
2. We also want to review the code for similar usecases.

NMIS setup on ESH is wip which will possibly uncover more for bits for (2).

```
--- /usr/lib64/perl5/vendor_perl/5.26.2/nmis4/SNMP_MIB.pm	2019-01-22 11:18:06.813450883 +0100
+++ /usr/lib64/perl5/vendor_perl/5.26.2/nmis4/SNMP_MIB.pm	2019-01-22 11:17:29.142708641 +0100
@@ -313,7 +313,7 @@
 	    $buf =~ s/OBJECT-TYPE/OBJECT IDENTIFIER/;
 	    $buf =~ s/MODULE-IDENTITY/OBJECT IDENTIFIER/;
 	    $buf =~ s/ IMPORTS .*\;//;
-	    $buf =~ s/ SEQUENCE {.*}//;
+	    $buf =~ s/ SEQUENCE \{.*\}//;
 	    $buf =~ s/ ([\w\-]+) ::= TEXTUAL-CONVENTION .* SYNTAX INTEGER \{/ $1 ::= INTEGER \{/;
 	    $buf =~ s/ [\w\-]+ ::= TEXTUAL-CONVENTION .* SYNTAX//;
 	    $buf =~ s/ SYNTAX INTEGER \{/ ::= INTEGER \{/;
```

**Comment by xmhd** [comment]
This builds fine with perl-5.30 + perl 5.32 - does this issue still need to be open @alip  ?

**Comment by xmhd** [comment]
isolating nmis where it is used
