### ISSUE TITLE
buildkernel test failures

### ISSUE THREAD

**Issue by ferki** [adjust/gentoo-overlay#25]
Looks like the master branch fails tests since [Build #162](https://travis-ci.org/adjust/gentoo-overlay/builds/155321154). All failures seems to be related to `sys-kernel/buildkernel`, and I guess this situation was introduced by an accidental merge/push directly to master.

Unfortunately branching off from a failing tree makes all subsequent builds to fail too, even if the changes on new PRs are fine by themselves.

@patricklauer: could you take a look, please?

**Comment by patricklauer** [comment]
Upstream pruned dependencies - gentoo-sources is now being punted at an annoyingly high rate. 

Everything cleaned up, shouldn't break for the next 2 weeks or so ...
