### ISSUE TITLE
dev-db/postgresql breaks building extensions

### ISSUE THREAD

**Issue by alexeyklyukin** [adjust/gentoo-overlay#279]
For our PostgreSQL packages, pg_config --libs reports the following libraries installed:

```
$ pg_config --libs
-lpgcommon -lpgport -lpthread -lpam -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm

```

However,` libpgcommon` and `libpgport` are actually missing from the system, breaking PostgreSQL extensions that require them to build (the particular one I'm looking into is pg_repack):

```
 ~/pg_repack $ make
make[1]: Entering directory '/var/lib/postgresql/pg_repack/bin'
x86_64-pc-linux-gnu-gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -pipe -ggdb -march=haswell pg_repack.o pgut/pgut.o pgut/pgut-fe.o  -L/usr/lib64/postgresql-10/lib64 -Wl,-O1 -Wl,--as-needed  -Wl,--as-needed -Wl,-rpath,'/usr/lib64/postgresql-10/lib64',--enable-new-dtags -Wl,-O1 -Wl,--as-needed -L/usr/lib64/postgresql-10/lib64 -lpq -L/usr/lib64/postgresql-10/lib64 -lpgcommon -lpgport -lpthread -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm -o pg_repack
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgcommon
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
```

The libraries are removed by our overlay:

https://github.com/adjust/gentoo-overlay/blob/b444ce0add8c63c5f7aa3a62374c00a6bca75d42/dev-db/postgresql/postgresql-10.9.ebuild#L247

that has been apparently cloned from the stock gentoo packages, however, there has been a bug report (https://bugs.gentoo.org/571046) and a fix (https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=edcac752028d3a882dbc2f64e37e1e95dff21276)  related to this specific issue that didn't make it to our packages.

Essentially, what I need is the following change:

```
@@ -208,7 +212,11 @@ src_install() {
 	insinto /etc/postgresql-${SLOT}
 	newins src/bin/psql/psqlrc.sample psqlrc
-	use static-libs || find "${ED}" -name '*.a' -delete
+	# Don't delete libpg{port,common}.a (Bug #571046). They're always
+	# needed by extensions utilizing PGXS.
+	use static-libs || \
+		find "${ED}" -name '*.a' ! -name libpgport.a ! -name libpgcommon.a \
+			 -delete
```

Please, bring our packages up-to-date so that we could have two libraries on the system and be able to compile extensions there.

**Comment by 65278** [comment]
Is this fix also applicable to postgres-11?

**Comment by alexeyklyukin** [comment]
I haven't tested it obviously, but the particular lines I highlighted should be applicable, as those files exist in every version supported by our overlay.

**Comment by 65278** [comment]
I'm asking because gentoo has only updated postgres's 10.9 ebuild
