### ISSUE TITLE
Create jupyterhub and dependencies ebuild

### ISSUE THREAD

**Issue by lemanchester** [adjust/gentoo-overlay#623]
We need jupyterhub and dependencies package into a ebuild

We had a PR in the past but never moved forward:

https://github.com/adjust/gentoo-overlay/pull/261

**Comment by xmhd** [comment]
how soon do we require these?

**Comment by nesat** [comment]
Hey @xmhd it is one of our top priority infrastructure requests. Another one is already on hold: https://github.com/adjust/infrastructure/issues/12649

Furthermore, this one was requested in 2019 so it would be great if we could have it soon, by the end of this quarter if possible

**Comment by xmhd** [comment]
> Hey @xmhd it is one of our top priority infrastructure requests. Another one is already on hold: [adjust/infrastructure#12649](https://github.com/adjust/infrastructure/issues/12649)
> 
> Furthermore, this one was requested in 2019 so it would be great if we could have it soon, by the end of this quarter if possible

@nesat ack, I've opened the PR for this @ overlay, should be merged soon. I will update you.

**Comment by xmhd** [comment]
merged
