### ISSUE TITLE
add elasticsearch-exporter package to ovelay

### ISSUE THREAD

**Issue by oziey88** [adjust/gentoo-overlay#630]
As we want to monitor elasticsearch using prometheus, we have to install elasticsearch-exporter with version 1.2.1 on the elasticsearch server.
Source: https://github.com/prometheus-community/elasticsearch_exporter/releases/tag/v1.2.1

we do have gentoo package for that (https://packages.gentoo.org/packages/app-metrics/elasticsearch_exporter)
but the version is not updated with the upstream, https://github.com/prometheus-community/elasticsearch_exporter/releases

I already tested to use elasticsearch_exporter v1.1.0 (latest version on gentoo package), and it's not well supported with our elasticsearch v7.13

Describe the solution you'd like
add elasticsearch_exporter v1.2.1 to our gentoo overlay

Describe alternatives you've considered
ping maintainer of elasticsearch_exporter gentoo to update the version with upstream

Additional context

**Comment by xmhd** [comment]
will ask the maintainer to ver bump in ::gentoo to avoid forking the package

**Comment by xmhd** [comment]
will chase this upstream as I don't really want to fork packages if it can be avoided.
