### ISSUE TITLE
app-admin/rex doesn't declare all rdeps

### ISSUE THREAD

**Issue by 65278** [adjust/gentoo-overlay#643]
We add support for  Idrac4/ILO with the following patches.
```
files/adjust_patches/0003-Shell.pm-add-iDRAC-4.00.00.00-support.patch
files/adjust_patches/0004-Shell.pm-add-iLO-support.patch
```

For this to work, we'd need to rdepend on :
```
 dev-perl/Rex-Interface-Shell-Ilo
 dev-perl/Rex-Interface-Shell-Idrac4 
```
Since we don't, rex breaks.

Either mask the package or fix rdepend please.

**Comment by monsieurp** [comment]
I will take a look at it.

**Comment by monsieurp** [comment]
@65278 fixed, please try again and report back, thanks!

**Comment by 65278** [comment]
Thanks. Unfortunately it appears that the package broke again by a commit from yesterday:
```
app-admin/rex-1.13.3::adjust (masked by: missing keyword)
```
This is commit b86c8616a760d36ef6dc82ce12a5f35429e2f46f. I don't quite get the logic here.
