### ISSUE TITLE
create ebuild for supervisord_exporter

### ISSUE THREAD

**Issue by zegeek** [adjust/gentoo-overlay#670]
I created a script to continuously monitor the  cpu and memory usage of jobs managed by supervisord. It dumps a prometheus exporter file that will be parsed by node_exporter and sent to prometheus servers. 
example: https://grafana.adjust.com/d/1iuqrccnz/acquired-supervisord-jobs-monitoring?orgId=1&refresh=1m

**Comment by xmhd** [comment]
merged , closing
